config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"
  get "/sign_up", to: "users#new"
  get "/dashboard", to: "users#show"

  resources :users, only: [:create]
  resources :links

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :links
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
    validates :url, :url => true
    belongs_to :user
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  validates_uniqueness_of :email
  validates_confirmation_of :password, message: 'password should match'
  has_secure_password
  has_many :links
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::Base
  protect_from_forgery with: :null_session
  respond_to :json

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < Api::ApiController
  respond_to :json

  def index
    user = current_user
    respond_with user.links.order('id')
  end

  def show
    user = User.find(params[:id])
    respond_with user.links.find(params[:link][:id])
  end

  def create
    user = current_user
    link = user.links.create(link_params)
    if link.save
      respond_with link
    end
  end

  def destroy
    user = User.find(params[:id])
    respond_with status: 204 if user.links.delete(params[:id])
  end

  def update
    link = Link.find(params[:link][:id])
    respond_with link.update(link_params)
  end

  private

    def link_params
      params.require(:link).permit(:id, :title, :url, :read, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_user

  # TODO: get this flash message working and tested

  def create
    @link = @user.links.create(link_params)
    if @link.save
    else
      flash[:notice] = "Invalid url, please try a valid web address"
    end
    redirect_to links_path
  end

  def index
    @link = @user.links.new
    @links = @user.links
  end

  def update
    @link = Link.find_by(params[:id])
    @link.update(link_params)
    redirect_to links_path
  end

  private

    def set_user
      @user = current_user
    end

    def link_params
      params.require(:link).permit(:id, :title, :url, :read, :user_id)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      flash.now[:error] = "Invalid Credentials"
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      flash.now[:error] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @user = User.find(current_user.id)
  end

  private

    def user_params
      params.require(:user).permit(:id, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThoughtBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
</head>
<body>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<div class="container">
  <h1>Submit a New Link</h1>

  <%= form_for(@link) do |f| %>
    <%= f.text_field :title, placeholder: "Title", class:"form-control" %><br>
    <%= f.text_field :url, placeholder: "URL", class:"form-control" %><br>
    <%= f.submit "Save Link", class:"btn btn-primary"%>
  <% end %>
<div id="baby-fake-button">
  <p>Looks Like a button</p>
</div>

  <div class="fake-form">
    <input type="text" id="fake-form-title" value="" placeholder="title">
    <input type="text" id="fake-form-url" value=""placeholder="url">
  </div>

  <h1>My Links</h1>
    <div id="links-div">
      <table id="links-table">

      </table>
    </div>
</div>

app/views/pages/home.html.erb
<%= link_to "Log In", login_path %>
<%= link_to "Sign Up", sign_up_path %>

app/views/users/new.html.erb
<div class="container">
  <h1>Register</h1>

  <%= form_for(@user) do |f| %>
  <%= f.text_field :email, placeholder: "Email", class:"form-control" %><br>
  <%= f.password_field :password, placeholder: "Password", class:"form-control" %><br>
  <%= f.password_field :password_confirmation, placeholder: "Password Confirmation", class:"form-control" %><br>
  <%= f.submit "Create Account", class:"btn btn-primary"%>

  <% end %>

</div>

app/views/users/show.html.erb
<h1>User Dashboard</h1>

<%= @user.email %>

<%= link_to "Logout", logout_path, method: :delete %>

<%= link_to "My Links", links_path %>